### ISSUE TITLE
isSkeleonable property doesn't work

### ISSUE THREAD

**Issue by R-U-N** [Juanpe/SkeletonView#81] opened 2018-07-25 08:06 UTC
⚠️ Please fill out this template when filing an issue.

### What did you do?

*I set the view's isSkeleonable property to false via IBInspector,and then call showAnimatedGradientSkeleton() after viewDidAppear

### What did you expect to happen?

*The view didn't showSkeleton

### What happened instead?

*The view showSkeleton

### Steps to reproduce the behavior

*I set the view's isSkeleonable property to false via IBInspector,and then call showAnimatedGradientSkeleton() after viewDidAppear

### SkeletonView Environment

**SkeletonView I test in demo downloaded frome Githud:** 
**Xcode 9.4:**
**Swift 4.0:**
<img width="1199" alt="2018-07-25 4 06 12" src="https://user-images.githubusercontent.com/22491697/43187688-b74a817e-9024-11e8-951b-9095bce4c2c7.png">

**Comment by Juanpe** [comment] 2018-07-26 12:10
Hi @R-U-N, I don't understand very well your issue. Actually if you want to show the skeleton in your views, you need to set `isSkeletonable` to `true`, instead of `false`

**Comment by R-U-N** [comment] 2018-07-30 07:00
Hi @Juanpe ,you see,if i have a lot of skeletonable item contained by a superview,and i just want some of them to show skeleton,so i set the true value to those item i want to shwo skeleton and false to those i don't want them to show skeleton.Then i call showAnimatedGradienSkeleton method for the superview.As a result,all items in the superview(including the superview itself) show sekeleton,just because the isSkeletonable porperty doesn't work.

**Comment by Juanpe** [comment] 2018-08-05 09:03
Hi @R-U-N, when superview (container view) show the skeleton is because it doesn't have children skeletonables. So, what is your view hierarchy? Something like this: 
```
[superview (skeletonable)]
  -- [view 1 (skeletonable)]
  -- [view 2 ( NO skeletonable)]
```

**Comment by R-U-N** [comment] 2018-08-06 01:45
Hi @Juanpe  ,my view hierarchy like this:

`[superview (NO skeletonable)]
  -- [view 1 (skeletonable)]
  -- [view 2 ( NO skeletonable)]`

but when I call the method showSkeleton for superview,the superview show sekeleton itself,which mask its child view skeleton effect.

**Comment by eduardbosch** [comment] 2019-05-22 19:20
It looks like this issue is a duplicate of this https://github.com/Juanpe/SkeletonView/issues/22

I've just created a PR with a fix to match the documentation definition: https://github.com/Juanpe/SkeletonView/pull/152

**Comment by eduardbosch** [comment] 2019-05-22 19:23
Duplicate of #22

I've just created a PR with a fix to match the documentation definition: https://github.com/Juanpe/SkeletonView/pull/152

**Comment by eduardbosch** [comment] 2019-05-22 19:23
Duplicate of #22

**Comment by eduardbosch** [comment] 2019-05-22 19:23
I've just created a PR with a fix to match the documentation definition: https://github.com/Juanpe/SkeletonView/pull/152

**Closed** 2019-08-27 18:24 UTC
Labels: question
