### ISSUE TITLE
automaticDimension is ignored, only estimatedRowHeight is used as Height

### ISSUE THREAD

**Issue by peterpaulis** [Juanpe/SkeletonView#468] opened 2021-11-30 14:49 UTC
### Description

The height of the skeleton cell should be calculated using autolayout based upon it's content, but the cell has always the height from estimatedRowHeight, no matter when providing delegate or rowHeight == UITableView.automaticDimension

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [X] bug
- [X] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [X] I've read and understood the [Contributing guidelines](https://github.com/Juanpe/SkeletonView/blob/main/CONTRIBUTING.md) and have done my best effort to follow them.
* [X] I've read and agree to the [Code of Conduct](https://github.com/Juanpe/SkeletonView/blob/main/CODE_OF_CONDUCT.md).
* [X] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

### SkeletonView Environment:

**SkeletonView version:1.26.0 **
**Xcode version:13.1 (13A1030d)**
**Swift version:5**

#### Steps to reproduce:

The height of the skeleton cell should be calculated using autolayout based upon it's content, but the cell has always the height from estimatedRowHeight, no matter when providing delegate or rowHeight == UITableView.automaticDimension

the docu only states 

1️⃣ If you are using resizable cells (tableView.rowHeight = UITableViewAutomaticDimension), it's mandatory define the estimatedRowHeight.

but not, that the an exact size is the only option and you are left out of automaticDimension :( so i suppose this is a bug?

#### Expected result:

height of the sekelton cell should be based upon UITableView.automaticDimension not estimatedRowHeight

#### Actual result:

estimatedRowHeight is always used, no matter the content

**Comment by Juanpe** [comment] 2021-11-30 15:02
Hi @peterpaulis 👋🏼 

Yep, you're right. Now, SkeletonView neither calculates the height of the cells nor considers the value provided by the delegate.

There is an open PR to allow to specify the height for each cell. #460

**Comment by peterpaulis** [comment] 2021-12-01 16:58
i believe this to be a very important feature... as you can display the table with different kinds of cells, have the skeleton cell match the content (like when you have a text size setting) or have random skeleton content (which changes the height)... looking forward for this to be added to main

**Comment by Juanpe** [comment] 2022-01-07 16:28
Duplicate of #424

**Closed by Juanpe** 2022-01-07 16:28 UTC
Labels: 💡 enhancement, 🚧 work in progress, triaged
