### ISSUE TITLE
Could not find module 'SkeletonView' for target 'x86_64-apple-ios-simulator'; found: arm64, arm64-apple-ios-simulator on M1 Chip

### ISSUE THREAD

**Issue by NilayDagdemir** [Juanpe/SkeletonView#486] opened 2022-01-26 08:22 UTC
### Description

SkeletonView fails when try to run my ui tests via fastlane command on a Mac Mini with M1 chip.

### Issue Type
- [x] bug
- [x] enhancement (feature request)
- [x] question

### Requirements
* [x] I've read and understood the [Contributing guidelines](https://github.com/Juanpe/SkeletonView/blob/main/CONTRIBUTING.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://github.com/Juanpe/SkeletonView/blob/main/CODE_OF_CONDUCT.md).
* [x] I've searched for any related issues and avoided creating a duplicate issue.
* [x] I've excluded arm64 architecture for Any iOS Simulator SDK on Build Settings.
* [x] I'm running Xcode with Rosetta

---

### Bug Report

I recieve this error when I try to run my ui tests via fastlane command on a Mac Mini with M1 chip:
 
`could not find module 'SkeletonView' for target 'x86_64-apple-ios-simulator'; found: arm64, arm64-apple-ios-simulator, at: /[DEVELOPER_PATH]/Xcode/DerivedData/[PROJECT_NAME]-aszrsdazdfzrgyelpmnfdgehbkgb/Build/Products/Debug-iphonesimulator/SkeletonView.swiftmodule`

On Macbook with an intel chip, it's working without an error.

### Fastlane Command
This is the lane that I'm using in order to run UI tests:
```
    test_simulators = ["iPhone 8","iPhone 11","iPhone 12 Pro Max"]

    desc "Run UI Tests"
    lane :run_ui_tests do
      run_tests(
        scheme: "[MY UI TEST SCHEME NAME]", # Project scheme name
        clean: true, # Clean project folder before test execution
        devices: test_simulators, # Simulator for testing
        reset_simulator: true
      )
    end
```

### SkeletonView Environment:

I installed the SkeletonView using swift package manager.

**SkeletonView version:1.25.1**
**Xcode version: 13.2.1**
**Swift version:5.5**

#### Expected result:

`Test Succeeded`

#### Actual result:

`Could not find module 'SkeletonView' for target 'x86_64-apple-ios-simulator'; found: arm64, arm64-apple-ios-simulator on M1 Chip`

**Comment by Capotasto** [comment] 2022-03-09 01:23
@NilayDagdemir Have you solved this problem? I'd like to use latest version of brew's cocoapods instead of using `Rosetta` or `arch -x86_64` .

**Comment by albyok** [comment] 2022-06-29 13:34
Got the exactly same problem. Is there a way to fix it?

**Comment by Capotasto** [comment] 2022-07-16 02:14
@albyok I was using the SkeltonView via Swift Package but it looks like there is not way to build with M1 mac. So I just change it to CocoaPods with the below code in Podfile.

```
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
    end
  end
end
```

**Comment by wohral** [comment] 2022-08-08 11:14
Got the same problem. Any progress with solving this bug?

**Comment by Juanpe** [comment] 2022-08-11 19:03
Hi mates! Now, [`SkeletonView` supports **XCFrameworks**](https://github.com/Juanpe/SkeletonView-XCFramework). Please, could you check if the problem is solved using XCFramework instead?

Thanks!

**Comment by wohral** [comment] 2022-08-12 09:39
> Hi mates! Now, [`SkeletonView` supports **XCFrameworks**](https://github.com/Juanpe/SkeletonView-XCFramework). Please, could you check if the problem is solved using XCFramework instead?
> 
> Thanks!

Thank you. It works! :)

**Comment by Juanpe** [comment] 2022-08-12 10:36
Great! So, I'm going to close this issue. Feel free to open a new one if you face another problem  😉

**Closed** 2022-08-12 10:36 UTC
Labels: ✅ fixed, triaged
