### ISSUE TITLE
SkeletonView-Swift.h

### ISSUE THREAD

**Issue by tikeyc** [Juanpe/SkeletonView#36] opened 2018-01-26 10:15 UTC
### What did you do?

Pure OC Project Import SkeletonView

### What did you expect to happen?

#import <SkeletonView/SkeletonView-Swift.h>

### What happened instead?

SkeletonView-Swift.h in the code is not complete

### Steps to reproduce the behavior

#import <SkeletonView/SkeletonView-Swift.h>

### SkeletonView Environment

SkeletonView version: 1.0.4
Xcode version: 9.2 (9C40b)
Swift version: 3.2

SkeletonView-Swift.h code is as follows:
```
SWIFT_MODULE_NAMESPACE_PUSH("SkeletonView")








@class CAAnimation;

@interface CALayer (SWIFT_EXTENSION(SkeletonView))
@property (nonatomic, readonly, strong) CAAnimation * _Nonnull pulse;
@property (nonatomic, readonly, strong) CAAnimation * _Nonnull sliding;
- (void)playAnimation:(SWIFT_NOESCAPE CAAnimation * _Nonnull (^ _Nonnull)(CALayer * _Nonnull))anim key:(NSString * _Nonnull)key;
- (void)stopAnimationForKey:(NSString * _Nonnull)key;
@end




@interface UIColor (SWIFT_EXTENSION(SkeletonView))
@property (nonatomic, readonly, strong) UIColor * _Nonnull complementaryColor;
@property (nonatomic, readonly, strong) UIColor * _Nonnull lighter;
@property (nonatomic, readonly, strong) UIColor * _Nonnull darker;
@end


@interface UIColor (SWIFT_EXTENSION(SkeletonView))
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, strong) UIColor * _Nonnull greenSea;)
+ (UIColor * _Nonnull)greenSea SWIFT_WARN_UNUSED_RESULT;
+ (void)setGreenSea:(UIColor * _Nonnull)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, strong) UIColor * _Nonnull turquoise;)
+ (UIColor * _Nonnull)turquoise SWIFT_WARN_UNUSED_RESULT;
+ (void)setTurquoise:(UIColor * _Nonnull)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, strong) UIColor * _Nonnull emerald;)
+ (UIColor * _Nonnull)emerald SWIFT_WARN_UNUSED_RESULT;
+ (void)setEmerald:(UIColor * _Nonnull)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, strong) UIColor * _Nonnull peterRiver;)
+ (UIColor * _Nonnull)peterRiver SWIFT_WARN_UNUSED_RESULT;
+ (void)setPeterRiver:(UIColor * _Nonnull)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, strong) UIColor * _Nonnull amethyst;)
+ (UIColor * _Nonnull)amethyst SWIFT_WARN_UNUSED_RESULT;
+ (void)setAmethyst:(UIColor * _Nonnull)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, strong) UIColor * _Nonnull wetAsphalt;)
+ (UIColor * _Nonnull)wetAsphalt SWIFT_WARN_UNUSED_RESULT;
+ (void)setWetAsphalt:(UIColor * _Nonnull)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, strong) UIColor * _Nonnull nephritis;)
+ (UIColor * _Nonnull)nephritis SWIFT_WARN_UNUSED_RESULT;
+ (void)setNephritis:(UIColor * _Nonnull)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, strong) UIColor * _Nonnull belizeHole;)
+ (UIColor * _Nonnull)belizeHole SWIFT_WARN_UNUSED_RESULT;
+ (void)setBelizeHole:(UIColor * _Nonnull)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, strong) UIColor * _Nonnull wisteria;)
+ (UIColor * _Nonnull)wisteria SWIFT_WARN_UNUSED_RESULT;
+ (void)setWisteria:(UIColor * _Nonnull)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, strong) UIColor * _Nonnull midnightBlue;)
+ (UIColor * _Nonnull)midnightBlue SWIFT_WARN_UNUSED_RESULT;
+ (void)setMidnightBlue:(UIColor * _Nonnull)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, strong) UIColor * _Nonnull sunFlower;)
+ (UIColor * _Nonnull)sunFlower SWIFT_WARN_UNUSED_RESULT;
+ (void)setSunFlower:(UIColor * _Nonnull)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, strong) UIColor * _Nonnull carrot;)
+ (UIColor * _Nonnull)carrot SWIFT_WARN_UNUSED_RESULT;
+ (void)setCarrot:(UIColor * _Nonnull)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, strong) UIColor * _Nonnull alizarin;)
+ (UIColor * _Nonnull)alizarin SWIFT_WARN_UNUSED_RESULT;
+ (void)setAlizarin:(UIColor * _Nonnull)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, strong) UIColor * _Nonnull clouds;)
+ (UIColor * _Nonnull)clouds SWIFT_WARN_UNUSED_RESULT;
+ (void)setClouds:(UIColor * _Nonnull)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, strong) UIColor * _Nonnull concrete;)
+ (UIColor * _Nonnull)concrete SWIFT_WARN_UNUSED_RESULT;
+ (void)setConcrete:(UIColor * _Nonnull)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, strong) UIColor * _Nonnull flatOrange;)
+ (UIColor * _Nonnull)flatOrange SWIFT_WARN_UNUSED_RESULT;
+ (void)setFlatOrange:(UIColor * _Nonnull)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, strong) UIColor * _Nonnull pumpkin;)
+ (UIColor * _Nonnull)pumpkin SWIFT_WARN_UNUSED_RESULT;
+ (void)setPumpkin:(UIColor * _Nonnull)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, strong) UIColor * _Nonnull pomegranate;)
+ (UIColor * _Nonnull)pomegranate SWIFT_WARN_UNUSED_RESULT;
+ (void)setPomegranate:(UIColor * _Nonnull)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, strong) UIColor * _Nonnull silver;)
+ (UIColor * _Nonnull)silver SWIFT_WARN_UNUSED_RESULT;
+ (void)setSilver:(UIColor * _Nonnull)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, strong) UIColor * _Nonnull asbestos;)
+ (UIColor * _Nonnull)asbestos SWIFT_WARN_UNUSED_RESULT;
+ (void)setAsbestos:(UIColor * _Nonnull)value;
@end






@interface UILabel (SWIFT_EXTENSION(SkeletonView))
@property (nonatomic) NSInteger lastLineFillPercent;
@end














@interface UITextView (SWIFT_EXTENSION(SkeletonView))
@property (nonatomic) NSInteger lastLineFillPercent;
@end














@interface UIView (SWIFT_EXTENSION(SkeletonView))
- (void)showSkeletonUsingColor:(UIColor * _Nonnull)color;
- (void)showAnimatedSkeletonUsingColor:(UIColor * _Nonnull)color animation:(CAAnimation * _Nonnull (^ _Nullable)(CALayer * _Nonnull))animation;
- (void)hideSkeletonWithReloadDataAfter:(BOOL)reload;
- (void)startSkeletonAnimation:(CAAnimation * _Nonnull (^ _Nullable)(CALayer * _Nonnull))anim;
- (void)stopSkeletonAnimation;
@end


@interface UIView (SWIFT_EXTENSION(SkeletonView))
@property (nonatomic) BOOL isSkeletonable;
@property (nonatomic, readonly) BOOL isSkeletonActive;
@end





SWIFT_MODULE_NAMESPACE_POP
#pragma clang diagnostic pop
```

**Comment by Juanpe** [comment] 2018-02-02 17:51
Hi @tikeyc, I'm working on this 😉

**Comment by tikeyc** [comment] 2018-03-14 01:40
@Juanpe Has the issue been solved?

**Comment by Juanpe** [comment] 2019-05-09 09:59
Duplicate of #32

**Closed by Juanpe** 2019-05-09 09:59 UTC
Labels: enhancement
