### ISSUE TITLE
UITableViewAutomaticDimension not working

### ISSUE THREAD

**Issue by denis-ios** [Juanpe/SkeletonView#37] opened 2018-02-05 13:20 UTC
⚠️ Please fill out this template when filing an issue.

### What did you do?

import SkeletonView
conform to 'SkeletonTableViewDataSource' and return cell identifier.
tableView.isSkeletonable = true
tableView.showSkeleton() before loading and tableView.hideSkeleton() after data is received.
tableview with rowHeight as default (UITableViewAutomaticDimension)
tableview with custom tableviewcell with a multiline with constraints to superview.

### What did you expect to happen?

cell height should grow with the text

### What happened instead?

cell height is equal to estimatedRowHeight
SkeletonView version 1.0.4 works as expected 

### SkeletonView Environment

**SkeletonView version:** 1.0.5
**Xcode version:** 9.2
**Swift version:** 4.0

**Comment by Juanpe** [comment] 2018-02-05 14:18
Hi @denis-ios, I'm going to check it.

**Comment by theblixguy** [comment] 2018-02-10 01:22
I have a similar issue. I am using v1.1. What's happening with me is:

* The skeleton view does not show, the UITableView shows a grey background
* The size of the UITableViewCells change on their own after I call `myTableView.hideSkeleton()`, which is really weird.

**Comment by Juanpe** [comment] 2018-02-14 08:48
Duplicate of #40

**Closed by Juanpe** 2018-02-14 08:48 UTC
Labels: bug
