### ISSUE TITLE
Add support for UICollectionViewDiffableDataSource and UITableViewDiffableDataSource

### ISSUE THREAD

**Issue by guidev** [Juanpe/SkeletonView#334] opened 2020-09-18 23:44 UTC
### Description

It would be awesome to add support for the (not so much) new `UICollectionViewDiffableDataSource` and `UITableViewDiffableDataSource`.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [x] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/Juanpe/SkeletonView/blob/develop/CONTRIBUTING.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://github.com/Juanpe/SkeletonView/blob/develop/CODE_OF_CONDUCT.md).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

**Comment by Juanpe** [comment] 2020-09-23 12:20
Duplicate of #279 

Hi @guidev, I'm going to close this issue because it's duplicated

**Comment by Juanpe** [comment] 2020-09-23 12:21
Hi @guidev, I'm going to close this issue because it's duplicated

**Closed by Juanpe** 2020-09-23 12:21 UTC
Labels: help wanted, 💡 enhancement
