### ISSUE TITLE
Diffable dataSource 

### ISSUE THREAD

**Issue by adelbios** [Juanpe/SkeletonView#322] opened 2020-09-07 15:51 UTC
Can you support a new logic of apple that used on ios 13 tableView and collectionView diffableDataSource*

**Comment by Juanpe** [comment] 2020-09-08 08:49
Hi @adelbios, this would be nice. Added to the backlog

**Comment by Juanpe** [comment] 2020-09-08 12:20
Duplicate of #279

**Closed** 2020-09-08 12:21 UTC
Labels: 👥 duplicated
