### ISSUE TITLE
Issue displaying skeleton view on all table view cells

### ISSUE THREAD

**Issue by JordanPJamieson** [Juanpe/SkeletonView#85] opened 2018-08-03 13:42 UTC
⚠️ Please fill out this template when filing an issue.

### What did you do?
Added skeleton view to my table view, implemented all of the required methods, and set the estimatedRowHeight as suggested by others.

### What did you expect to happen?
I pass in a number for the numberOfRowsInSection method and it will display the skeleton view on that specified number of rows. 

### What happened instead?
Only the first three table view cells get covered by the skeleton view and the rest of the cells are just blank templates of the table view cell I created in the storyboard.  Maybe the height of my table needs to be changed because it's using the estimated number of rows instead?

### Steps to reproduce the behaviour
Create a table view and assign the number of rows in section and not every cell gets covered with a skeleton view.

### SkeletonView Environment

**SkeletonView version:**
Latest
**Xcode version:**
9.4
**Swift version:**
4

**Comment by Juanpe** [comment] 2018-08-05 09:06
Hi @JordanPJamieson. Could you give more info about your code? 
When and where are you calling the `showSkeleton` method?

**Comment by sungkim23** [comment] 2018-08-14 23:15
Had the same issue happen, only fixed when implementing

` tableView.rowHeight = UITableViewAutomaticDimension
   tableView.estimatedRowHeight = 150.0
`

**Comment by JordanPJamieson** [comment] 2018-09-11 13:30
Sorry for the late response, I fixed this issue by setting a default value instead of a dynamic value for the function:

collectionSkeletonView(_ skeletonView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return 10
    }

My API request wasn't retrieving the data in time to tell this method how many rows to display the skeleton view on before the function executed.

Thanks for the suggestions.

**Comment by BryanRyczek** [comment] 2018-10-11 02:48
I'm having the same issues where the last cells aren't covered by skeleton view. I've set these params:

**tableView.rowHeight = UITableViewAutomaticDimension
tableView.estimatedRowHeight = 100.0**

I also implemented this delegate function, which is behaving as expected. 

**collectionSkeletonView(_ skeletonView: UITableView, numberOfRowsInSection section: Int) -> Int {}**

I'm having the issues on these devices:

**-Iphone XS Max
-Iphone XR**

Other devices look fine.

`https://imgur.com/a/w66fdD8`

**Comment by BryanRyczek** [comment] 2018-10-11 03:17
^^ Just wanted to add that I changed my size class in the simulator from iPhone XS to iPhone Max and skeleton view renders properly on all devices. 

It seems as if the height of my table view was being calculated off the values from storyboard? Dunno.

**Comment by r00li** [comment] 2018-12-07 13:44
I can confirm what @BryanRyczek said here. The last cell was showing without skeleton on iPhones XR and XS until I changed the size class in the storyboard.

**Comment by NerdBird** [comment] 2019-04-03 21:55
I am seeing the same issue. Thanks @BryanRyczek for a solution! This has been driving me nuts.

**Comment by Juanpe** [comment] 2019-04-04 05:30
Thanks for the responses 👏🏼 
So we could close this issue, since it seems resolved, right?

**Comment by r00li** [comment] 2019-04-04 05:37
@Juanpe I wouldn't exactly call this resolved. It is a workaround, but it doesn't solve the issue. The size shouldn't depend on the storyboard values in the first place. If Apple makes a phone with an even taller screen all of the apps will break until somebody updates all of the storyboards again.

**Comment by BryanRyczek** [comment] 2019-04-04 16:47
I agree with @r00li, and want to add that if your app is meant for iPad as well as iPhone, you will see this issue on iPad if your size class is set for iPhone.

**Comment by BhavikThummar** [comment] 2019-04-08 02:49
Hello @Juanpe 
I had the same issue, please let me know when you get resolved it. Because size classes is not a permanent solution.

**Comment by PatrickAdams** [comment] 2019-04-10 17:26
I thought the `numberOfRowsInSection` method of SkeletonTableViewDataSource would solve this, but that's not the case either. It's ignoring anything over the calculated amount of rows. If it's calculating 5 rows and I set the number to 6 via that method, it ignores it and uses 5 rows. If I set it to 5 rows it at least hides the last un-skeletoned row. So that's another workaround.

**Comment by whoyawn** [comment] 2019-06-04 01:12
Running into a similar error here. I'm using an iPhone XR simulator and a iPhone XR device. When I set my storyboard to the Xs Max, the skeleton view covers 100% of the original view. When I use the iPhone 8 size class, it only covers 80% of the view at runtime.

**Comment by bentahyar** [comment] 2019-06-27 08:29
anyone had a fix on this yet?
I experince this on iPhone plus when using collectionview. Setting the size class didn't help at all

**Comment by Juanpe** [comment] 2019-08-23 11:34
Actually, you don't specify the number of rows, SkeletonView calculates how many rows should be shown based on table view height. 

The problem is if you are showing the skeletons when the view will appear, the views are not ready yet, so the skeleton doesn't work correctly. But if you show the skeleton when the view *did* appear, the problem should be solved. 

Another possible solution is calling the method `view.layoutSkeletonIfNeeded`. This method redraws the skeleton taking account of the new frames.

**Comment by whoyawn** [comment] 2019-10-22 18:22
Has this been fixed yet?

**Closed** 2019-12-28 19:30 UTC
Labels: given up, ⏳ awaiting user input, 🤔 possible bug
