### ISSUE TITLE
How can we use this SDK in objective c?

### ISSUE THREAD

**Issue by webappsllcInfo** [Juanpe/SkeletonView#123] opened 2018-12-20 07:18 UTC
⚠️ Please fill out this template when filing an issue.

### What did you do?

*Please replace this with what you did.*

### What did you expect to happen?

*Please replace this with what you expected to happen.*

### What happened instead?

*Please replace this with of what happened instead.*  

### Steps to reproduce the behavior

*Please replace this with the steps to reproduce the behavior.*

### SkeletonView Environment

**SkeletonView version:**
**Xcode version:**
**Swift version:**

**Comment by Juanpe** [comment] 2019-08-23 07:51
Duplicate of #32

**Closed by Juanpe** 2019-08-23 07:51 UTC
