### ISSUE TITLE
skeletonLayoutSubviews() is called infinitely when Open Floating Keyboard with Input AccessoryView after showAnimatedGradientSkeleton()

### ISSUE THREAD

**Issue by kanottonp** [Juanpe/SkeletonView#352] opened 2021-01-06 09:07 UTC
### Description

Describe your issue here.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ x] bug
- [ ] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [ x] I've read and understood the [Contributing guidelines](https://github.com/Juanpe/SkeletonView/blob/develop/CONTRIBUTING.md) and have done my best effort to follow them.
* [ x] I've read and agree to the [Code of Conduct](https://github.com/Juanpe/SkeletonView/blob/develop/CODE_OF_CONDUCT.md).
* [ x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

### SkeletonView Environment:

**SkeletonView version:*1.11.0*
**Xcode version:*12.3*
**Swift version:*5.3.2*

#### Steps to reproduce:

*Please replace this with the steps to reproduce the behavior.*

1. This Bug can only reproduce iPad or iPad emulator. Before the rest of steps, make sure that your keyboard is floated by using two finger pinches on docked keyboard.

2. Create an ad hoc Application with viewController that contains only one textView and one textField with inputAccessoryView like this
```swift
class ViewController: UIViewController {

    @IBOutlet weak var textView: UITextView!
    @IBOutlet weak var textField: UITextField!
    
    let inputAs = UIView()
    
    override func viewDidLoad() {
        super.viewDidLoad()
        textView.isSkeletonable = true
        textField.inputAccessoryView = inputAs
    }
    
    override func viewWillAppear(_ animated: Bool) {
        textView.showAnimatedGradientSkeleton()
    }
    
    override func viewDidAppear(_ animated: Bool) {
        textView.hideSkeleton()
    }
    
}
```
3. Open the app and then tap textField

#### Expected result:

Application can open keyboard that focusing to the textField properly

#### Actual result:

Boom!. App has been bricked. when 100% CPU and memory leaking

skeletonLayoutSubviews() is called infinitely

ps. when I logged inside skeletonLayoutSubviews() with `print(self)` I found this thing

```
<UIInputSetContainerView: 0x7ffc6562e7a0; frame = (0 0; 820 1180); gestureRecognizers = <NSArray: 0x6000026e85d0>; layer = <CALayer: 0x600002826c40>>
<_UIPopoverStandardChromeView: 0x7ffc63714a70; frame = (0 0; 334 308); layer = <CALayer: 0x6000028d3e40>>
<UIInputSetContainerView: 0x7ffc6562e7a0; frame = (0 0; 820 1180); gestureRecognizers = <NSArray: 0x6000026e85d0>; layer = <CALayer: 0x600002826c40>>
<_UIPopoverStandardChromeView: 0x7ffc63714a70; frame = (0 0; 334 308); layer = <CALayer: 0x6000028d3e40>>
<UIInputSetContainerView: 0x7ffc6562e7a0; frame = (0 0; 820 1180); gestureRecognizers = <NSArray: 0x6000026e85d0>; layer = <CALayer: 0x600002826c40>>
<_UIPopoverStandardChromeView: 0x7ffc63714a70; frame = (0 0; 334 308); layer = <CALayer: 0x6000028d3e40>>
<UIInputSetContainerView: 0x7ffc6562e7a0; frame = (0 0; 820 1180); gestureRecognizers = <NSArray: 0x6000026e85d0>; layer = <CALayer: 0x600002826c40>>
<_UIPopoverStandardChromeView: 0x7ffc63714a70; frame = (0 0; 334 308); layer = <CALayer: 0x6000028d3e40>>
<UIInputSetContainerView: 0x7ffc6562e7a0; frame = (0 0; 820 1180); gestureRecognizers = <NSArray: 0x6000026e85d0>; layer = <CALayer: 0x600002826c40>>
<_UIPopoverStandardChromeView: 0x7ffc63714a70; frame = (0 0; 334 308); layer = <CALayer: 0x6000028d3e40>>
<UIInputSetContainerView: 0x7ffc6562e7a0; frame = (0 0; 820 1180); gestureRecognizers = <NSArray: 0x6000026e85d0>; layer = <CALayer: 0x600002826c40>>
<_UIPopoverStandardChromeView: 0x7ffc63714a70; frame = (0 0; 334 308); layer = <CALayer: 0x6000028d3e40>>
<UIInputSetContainerView: 0x7ffc6562e7a0; frame = (0 0; 820 1180); gestureRecognizers = <NSArray: 0x6000026e85d0>; layer = <CALayer: 0x600002826c40>>
<_UIPopoverStandardChromeView: 0x7ffc63714a70; frame = (0 0; 334 308); layer = <CALayer: 0x6000028d3e40>>
<UIInputSetContainerView: 0x7ffc6562e7a0; frame = (0 0; 820 1180); gestureRecognizers = <NSArray: 0x6000026e85d0>; layer = <CALayer: 0x600002826c40>>
<_UIPopoverStandardChromeView: 0x7ffc63714a70; frame = (0 0; 334 308); layer = <CALayer: 0x6000028d3e40>>
<UIInputSetContainerView: 0x7ffc6562e7a0; frame = (0 0; 820 1180); gestureRecognizers = <NSArray: 0x6000026e85d0>; layer = <CALayer: 0x600002826c40>>
<_UIPopoverStandardChromeView: 0x7ffc63714a70; frame = (0 0; 334 308); layer = <CALayer: 0x6000028d3e40>>
```

It is called by only the same two components.

Hope this can help you.

#### Attachments:

Demo Video

https://user-images.githubusercontent.com/21222987/103750333-39eb1e00-5039-11eb-99cc-acc67a6ce1f3.mp4

**Comment by chalermpong** [comment] 2021-01-07 03:52
To summarize the problem here:
1. Set iPad to use Floating Keyboard
2. Create an app containing a TextField with any inputAccessoryView. 
3. Swizzling the `UIView.layoutSubviews` method
4. Run the app and click on the TextField -> App will be stuck in infinite loop

It seems to be an iOS problem here.  @Juanpe Is it possible to implement SkeletonView without swizzling `UIView.layoutSubviews`?

**Comment by Juanpe** [comment] 2021-01-14 12:38
Hi @chalermpong, thanks for sharing this bug and for trying to explain how to reproduce it. It's very useful to fix it.

I'm going to check it 👍

**Comment by alexookah** [comment] 2021-03-22 11:46
I am experiencing the same problem. when trying to move the floating keyboard to the bottom of the screen. The whole app freezes.

https://github.com/Juanpe/SkeletonView/blob/7d8a057b64dd8b823ba9e1272bd018a166aa226f/Sources/SkeletonView.swift#L96-L101

is self-calling itself. Maybe this should be handled differently?

**Comment by Juanpe** [comment] 2021-03-22 12:37
Hi @alexookah, I'm still looking for how to solve this problem :/ I hope I can find a solution soon

**Comment by alexookah** [comment] 2021-03-22 15:06
Here adding a video that demonstrates the problem:

https://user-images.githubusercontent.com/9624843/112011133-a2be3e80-8b30-11eb-8108-f9630c211258.mov

`
class Cell: UITableViewCell {
    
    @IBOutlet weak var avatar: UIImageView!
    @IBOutlet weak var label1: UILabel!
    @IBOutlet weak var textField: UITextField!

    override func awakeFromNib() {
        super.awakeFromNib()
        setUpInputAccessoryView()
    }

    func setUpInputAccessoryView() {
        let bar = UIToolbar()
        let reset = UIBarButtonItem(title: "InputAccessoryView", style: .plain, target: self, action: #selector(resetTapped))
        bar.items = [reset]
        bar.sizeToFit()
        textField.inputAccessoryView = bar
    }

    @objc func resetTapped() {

    }
}
`

**Comment by alexookah** [comment] 2021-04-07 07:34
Do we have any news about the issue?
maybe this helps the issue? https://github.com/Juanpe/SkeletonView/issues/358

**Comment by alexookah** [comment] 2021-04-07 18:22
@Juanpe 
Just added a PL that might be a solution :)

**Comment by Juanpe** [comment] 2021-04-08 10:47
Hi all, the latest version (1.14.0) contains a fix to solve this problem. I'm going to close this issue, feel free to open a new one if you still facing the problem.

Thanks @alexookah for the contribution

**Closed by Juanpe** 2021-04-08 10:47 UTC
Labels: 🤔 possible bug
