### ISSUE TITLE
Can you provide an example of RxDataSource

### ISSUE THREAD

**Issue by lumangmang** [Juanpe/SkeletonView#429] opened 2021-08-13 16:18 UTC

**Comment by Juanpe** [comment] 2021-08-17 16:47
Hi @lumangmang 👋🏼 

Today the library is not fully compatible with `RxDataSource`. We're working on this feature, but it's not ready yet. Meanwhile, you can create a fake `collectionview` / `tableview` that shows skeleton without using **Rx** and is hidden when data is received: /

**Comment by Juanpe** [comment] 2021-08-19 09:19
Duplicate of #370

**Closed by Juanpe** 2021-08-19 09:19 UTC
Labels: feature
