### ISSUE TITLE
Xcode 10, Swift 4.3 support required

### ISSUE THREAD

**Issue by asifbilal786** [Juanpe/SkeletonView#138] opened 2019-02-14 11:14 UTC
I am using this library and it's working great. But it's yet not build with Swift 4.3 as it's required for Xcode 10 now. Please add support for Swift 4.3 so that we can continue using it.

**Comment by Tavernari** [comment] 2019-02-15 13:49
I think the problem is when you try to use CocoaPods.

I forked the project and I put manually the project as a dependency of my main project and all things work well.

**Comment by Tavernari** [comment] 2019-02-19 18:56
@asifbilal786 I found this.

`pod 'SkeletonView', :git => 'https://github.com/Juanpe/SkeletonView.git', :branch => 'master'`

It will work.

**Comment by NikKovIos** [comment] 2019-04-30 13:19
Now @Tavernari answer is not actual, use commit `4fb8020c8321d0d9b525352dde58c0a0f3175c0b`

**Comment by eduardbosch** [comment] 2019-05-07 20:35
I'm closing this issue as version 1.5 of SkeletonView supports Swift 5.

**Closed by eduardbosch** 2019-05-07 20:35 UTC
