### ISSUE TITLE
TableView cell have a collection view bottom cell stills gradient view not removed when scroll upwards 

### ISSUE THREAD

**Issue by ramesh09ios** [Juanpe/SkeletonView#297] opened 2020-06-08 08:25 UTC
⚠️ Please fill out this template when filing an issue.

### What did you do?
Implement table view cell contain collection view Skelton view removing visiable cells but bottom cells have still Skelton view.
*Please replace this with what you did.*

### What did you expect to happen?

*Please replace this with what you expected to happen.*

### What happened instead?

*Please replace this with of what happened instead.*  

### Steps to reproduce the behavior

*Please replace this with the steps to reproduce the behavior.*

### SkeletonView Environment

**SkeletonView version:**
**Xcode version:**
**Swift version:**

**Comment by Juanpe** [comment] 2021-06-09 14:14
Hi @ramesh09ios,

I think this issue is the same of #399, please, check it in order to close this one :)

**Comment by Juanpe** [comment] 2021-06-09 14:15
Duplicate of #399

**Closed** 2021-06-09 14:16 UTC
