### ISSUE TITLE
how to use with RxSwift

### ISSUE THREAD

**Issue by kou-yamamoto** [Juanpe/SkeletonView#457] opened 2021-09-27 13:15 UTC
### Describe the feature or problem you’d like to solve

- Is there any way to use SkeltonView with RxSwift

### Additional context

- Please let me know if there is a people who use SlektonView with RxSwift.

**Comment by ahmedkoshek** [comment] 2021-12-11 18:55
@kou-yamamoto Did you find a way to use SkeletonView with RxSwift?

**Comment by kou-yamamoto** [comment] 2021-12-12 01:16
@ahmedkoshek I dound this `https://github.com/anyoptional/RxSkeleton` but was archived.

**Comment by Juanpe** [comment] 2022-01-10 15:49
I'm working on a version compatible with RxDataSource. When it's ready I'll create an example app to show how it works :)

**Comment by Juanpe** [comment] 2022-01-10 15:49
Duplicate of #370

**Closed by Juanpe** 2022-01-10 15:49 UTC
Labels: triaged
